### PR TITLE
Update Readme/Project Outline - Benchmark Goal

### PR DESCRIPTION
**Pull request by mistakeets**

### CODE REVIEW

**Review by jrobcodes — COMMENTED** [review]
I know we're not supposed to change benchmark goals, but I consider a codebase with test coverage a code base that is not the highest possible quality.  Consider adding a testing requirement for this benchmark goal - tests ensure the quality of the code by providing a (preferably automated) means of checking the correctness of your implementation.

**Comment by deonna** [comment]
@jrob8577 - there's a **Testing** section for the goal.

**Comment by jrobcodes** [comment]
@deonna Thanks, I missed that! I would love to see that as an explicit requirement for each solution (I imagine if I missed it, reviewers might miss it when evaluating completion and quality).  Maybe a section that enumerates the requirements, with check boxes, similar to how other goals are written?

**Comment by mistakeets** [comment]
I plan to use mocha/chai where I can for testing purposes. There are 1 or 2 of the exercises where I am not quite sure how I am going to implement tests yet and will reach out if needed on coach que :)

**Comment by deonna** [comment]
@jrob8577 - sure - a more explicit set of requirements sounds good. I'll add it for next cycle so I am not springing the new requirements on folks who have already committed to the current specs.

**Pull request merged**
